### ISSUE TITLE
AUR package do not pass the validity check

### ISSUE THREAD

**Issue by francozappa** [ARMmbed/cmsis-pack-manager#146]
Hi,

I'm trying to instal `python-cmsis-pack-manager`v0.2.10 from the Arch User Repo (AUR) and it does not pass the sha256sum validity check.

Could you help me?

**Comment by flit** [comment]
Hi @francozappa, we are not the maintainers of the AUR package. From the [package description](https://aur.archlinux.org/packages/python-cmsis-pack-manager/) on the AUR site, it looks like user 2bluesc is the maintainer. Also, the PKGBUILD has a comment that sasy: `Maintainer: Kyle Manna <kyle[at]kylemanna[d0t]com>`.

(Closing this issue since we can't help. Please reopen if you feel otherwise.)
